# Generated by Django 5.1.15 on 2026-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("MANUAL_GATE_OPEN", "Manual Gate Open"),
                    ("PRICE_CHANGE", "Price Rule Changed"),
                    ("SPOT_CREATED", "Parking Spot Created"),
                    ("SPOT_UPDATED", "Parking Spot Updated"),
                    ("SPOT_DELETED", "Parking Spot Deleted"),
                    ("USER_CREATED", "User Account Created"),
                    ("USER_DEACTIVATED", "User Account Deactivated"),
                    ("LOGIN_SUCCESS", "Successful Login"),
                    ("LOGIN_FAILED", "Failed Login Attempt"),
                    ("LOGOUT", "User Logout"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("TICKET_VOIDED", "Ticket Voided"),
                    ("OCCUPANCY_RESET", "Lot Occupancy Reset"),
                ],
                db_index=True,
                help_text="Semantic code for the action that took place.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                default=dict,
                help_text="Arbitrary JSON payload describing the change (e.g. old vs new values for price changes).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="TOTP base32 secret (pyotp). Empty string means 2FA is not yet configured. Only Admin accounts require 2FA per PRD §4.2.",
                max_length=64,
            ),
        ),
    ]
