# Generated by Django 5.1.15 on 2026-05-27 03:08

import apps.accounts.managers
from django.db import migrations, models


def promote_existing_superusers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).update(role="SUPERUSER")


def demote_existing_superusers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True, role="SUPERUSER").update(role="ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_auditlog_action_type_alter_auditlog_details_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "System Superuser"),
                    ("ADMIN", "Management Admin"),
                    ("ATTENDANT", "Parking Attendant"),
                ],
                db_index=True,
                default="ATTENDANT",
                help_text="The RBAC role that controls which endpoints this user may access.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            promote_existing_superusers,
            reverse_code=demote_existing_superusers,
        ),
    ]
