# Generated by Django 5.1.15 on 2026-03-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assigned_size",
            field=models.CharField(
                choices=[
                    ("COMPACT", "Compact"),
                    ("REGULAR", "Regular"),
                    ("OVERSIZED", "Oversized"),
                ],
                db_index=True,
                help_text="The spot-size actually reserved by OCC (may differ from the vehicle's preferred size when overflow applies).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="entry_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="UTC timestamp when the vehicle entered. Pricing clock starts here.",
            ),
        ),
    ]
