# Generated by Django 5.1.15 on 2026-03-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gates", "0002_alter_ticket_assigned_size_alter_ticket_entry_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTORCYCLE", "Motorcycle"),
                            ("CAR", "Car"),
                            ("TRUCK", "Truck"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "spot_size",
                    models.CharField(
                        choices=[
                            ("COMPACT", "Compact"),
                            ("REGULAR", "Regular"),
                            ("OVERSIZED", "Oversized"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("time_start", models.TimeField(help_text="Start time of this rule")),
                (
                    "time_end",
                    models.TimeField(help_text="End time of this rule (inclusive)"),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_daily_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments_pricing_rules",
                "ordering": ["vehicle_type", "spot_size", "time_start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("vehicle_type__in", ["MOTORCYCLE", "CAR", "TRUCK"])
                        ),
                        name="chk_pricing_vehicle_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("spot_size__in", ["COMPACT", "REGULAR", "OVERSIZED"])
                        ),
                        name="chk_pricing_spot_size_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CREDIT", "Credit Card"),
                            ("MOBILE", "Mobile App"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        db_index=True,
                        default="SUCCESS",
                        max_length=15,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="gates.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "payments_transactions",
                "ordering": ["-payment_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_method__in", ["CASH", "CREDIT", "MOBILE"])
                        ),
                        name="chk_payment_method_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["SUCCESS", "FAILED"])),
                        name="chk_payment_status_valid",
                    ),
                ],
            },
        ),
    ]
