# Generated by Django 5.1.15 on 2026-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspot",
            name="spot_number",
            field=models.CharField(
                help_text='Human-readable identifier, e.g. "A-001" or "COMPACT-0001".',
                max_length=20,
                unique=True,
            ),
        ),
    ]
