"""
Track 3 — Task 3.1: Tickets model

A Ticket is created when a vehicle successfully enters the lot (entry gate
reserves an OCC slot) and is closed when the vehicle pays and leaves (exit
gate releases the OCC slot in Track 4).

Design decisions
----------------
* ``ticket_code`` — 12-character uppercase alphanumeric, generated by
  _generate_code().  Unique, indexed, printed on the physical stub.
* ``vehicle_type`` — copied from the entry request (immutable after creation).
* ``assigned_size`` — the spot-size that was OCC-reserved.  Not necessarily
  the vehicle's preferred size (overflow applies).
* ``status`` — OPEN → PAID (Track 4) → VOIDED (Admin override).
* ``entry_time`` — set to now() on creation; the exit-pricing clock starts here.
* ``exit_time``  — null until payment completes (Track 4).
* FK to ``accounts.User`` (attendant or gate-hardware service account) with
  SET_NULL so a deleted attendant's tickets remain queryable.

Indexes
-------
* ``ticket_code`` — UNIQUE already creates an index; used for scan lookup.
* ``status``     — filter open/paid tickets (dashboard, revenue reports).
* ``(status, entry_time)`` — composite for "open tickets older than 7 days" query (Track 6).
* ``vehicle_type`` — optional analytics grouping.
"""
import random
import string

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.inventory.models import SpotSizeType, VehicleType


# ──────────────────────────────────────────────────────────────────
# Enumerations
# ──────────────────────────────────────────────────────────────────

class TicketStatus(models.TextChoices):
    OPEN   = "OPEN",   _("Open")   # Vehicle is currently in the lot
    PAID   = "PAID",   _("Paid")   # Vehicle paid and exited (Track 4)
    VOIDED = "VOIDED", _("Voided") # Admin override — ticket cancelled


# ──────────────────────────────────────────────────────────────────
# Helper
# ──────────────────────────────────────────────────────────────────

_CODE_ALPHABET = string.ascii_uppercase + string.digits  # 36 chars
_CODE_LENGTH   = 12                                       # ~2.2 × 10^18 space


def _generate_code() -> str:
    """
    Return a 12-char uppercase-alphanumeric ticket code (collision extremely
    rare at the scale of this system; uniqueness enforced at DB level).
    """
    return "".join(random.choices(_CODE_ALPHABET, k=_CODE_LENGTH))


# ──────────────────────────────────────────────────────────────────
# Task 3.1 — Ticket model
# ──────────────────────────────────────────────────────────────────

class Ticket(models.Model):
    """
    Represents one parking session from entry to exit.

    Lifecycle
    ---------
    Entry gate:  create Ticket (status=OPEN, entry_time=now)
    Exit scan:   Track 4 calculates fee; status remains OPEN until paid
    Payment:     Track 4 updates status=PAID, exit_time=now, restores OCC
    Admin void:  status=VOIDED via Admin gate-override endpoint
    """

    ticket_code = models.CharField(
        max_length=20,
        unique=True,
        default=_generate_code,
        db_index=True,
        help_text=_("Printed on the physical ticket stub. 12-char alphanumeric."),
    )
    vehicle_type = models.CharField(
        max_length=15,
        choices=VehicleType.choices,
        db_index=True,
        help_text=_("Vehicle class presented at the entry gate."),
    )
    assigned_size = models.CharField(
        max_length=10,
        choices=SpotSizeType.choices,
        db_index=True,
        help_text=_(
            "The spot-size actually reserved by OCC (may differ from the "
            "vehicle's preferred size when overflow applies)."
        ),
    )
    status = models.CharField(
        max_length=10,
        choices=TicketStatus.choices,
        default=TicketStatus.OPEN,
        db_index=True,
        help_text=_("Lifecycle state of the parking session."),
    )
    entry_time = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("UTC timestamp when the vehicle entered. Pricing clock starts here."),
    )
    exit_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("UTC timestamp when the vehicle exited and payment was confirmed."),
    )

    # Who issued / processed this ticket (gate attendant or Gate service account)
    issued_by = models.ForeignKey(
        "accounts.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="issued_tickets",
        help_text=_("Attendant / service account that created this ticket."),
    )

    class Meta:
        db_table  = "gates_tickets"
        ordering  = ["-entry_time"]
        indexes   = [
            # Open-ticket age scan — "find sessions older than N days"
            models.Index(
                fields=["status", "entry_time"],
                name="idx_tickets_status_entry",
            ),
            # Revenue aggregation by vehicle type + date range
            models.Index(
                fields=["vehicle_type", "entry_time"],
                name="idx_tickets_vehicle_entry",
            ),
        ]
        constraints = [
            models.CheckConstraint(
                check=models.Q(vehicle_type__in=VehicleType.values),
                name="chk_ticket_vehicle_type_valid",
            ),
            models.CheckConstraint(
                check=models.Q(assigned_size__in=SpotSizeType.values),
                name="chk_ticket_assigned_size_valid",
            ),
            models.CheckConstraint(
                check=models.Q(status__in=TicketStatus.values),
                name="chk_ticket_status_valid",
            ),
        ]

    def __str__(self) -> str:
        return f"[{self.ticket_code}] {self.vehicle_type} → {self.assigned_size} ({self.status})"

    @property
    def is_open(self) -> bool:
        return self.status == TicketStatus.OPEN
